### PR TITLE
Add `peerComponents` frontmatter attribute

### PR DESCRIPTION
**Pull request by wkentdag**
* Adds a `peerComponents` frontmatter attribute, enabling consumers to inject additional components into their `docs.mdx` contexts
* This is helpful for situations where you want to demo a pattern that includes multiple components. For example with Learn, a `<Carousel />` component could feature examples rendering both `<TutorialCard />` and `<CollectionCard />`.
* 🚨 peer components must also be present in swingset, and a warning gets emitted otherwise.

### CODE REVIEW

**Comment by BRKalow** [comment]
Nice!

I wonder if we could leverage actual import statements for this 🤔

```
import Button from '@swingset/components'
```

I'm not sure if it would actually improve anything though..

**Comment by wkentdag** [comment]
@BRKalow I thought lack of support for imports was a known caveat of `next-mdx-remote`? https://github.com/hashicorp/next-mdx-remote#caveats

**Comment by BRKalow** [comment]
@wkentdag Yep, I was more thinking of instrumenting something in swingset with a remark plugin where we would use import statements to effectively mark `peerComponents`, then remove the statements. Again, probably more trouble than just using frontmatter 😅

**Review by jescalan — APPROVED** [review]
This is great, love it. I like the idea of supporting certain types of imports with plugins as well, but that would be a bit larger of a project. I was thinking perhaps if you define a `root` option to mdx remote or something, we may be able to re-enable imports. But for now this feels like a good option!

**Pull request merged**
